-- Goldline (NICHIDO) catalog from the printed semi-monthly inventory form, pages 1–5.
-- Source: the blank templates' text layer (family heading + printed price, item code,
-- shade, "(Bestseller)" mark), matched item-by-item to the extraction manifests in
-- src/goldline-extract.ts. 263 items. Regenerate when the template changes.
--
-- Upsert on (company_id, item_code): sets product_line / variant / unit_price /
-- is_bestseller and leaves sku_code (the POS numeric crosswalk) untouched — the form
-- doesn't print POS codes. Idempotent; data only (no DDL). Staging first.

insert into public.gl_products (company_id, item_code, product_line, variant, unit_price, is_bestseller)
values
  ('goldline', 'FBPP01', 'Flawless Beauty Pressed Powder', 'Salmon', 150.00, false),
  ('goldline', 'FBPP02', 'Flawless Beauty Pressed Powder', 'Golden Tan', 150.00, true),
  ('goldline', 'FBPP03', 'Flawless Beauty Pressed Powder', 'Almond', 150.00, false),
  ('goldline', 'FBPP04', 'Flawless Beauty Pressed Powder', 'Sand', 150.00, false),
  ('goldline', 'FBPP05', 'Flawless Beauty Pressed Powder', 'Natural', 150.00, true),
  ('goldline', 'FCPP01131', 'Fancy Colors', 'Natural', 88.00, false),
  ('goldline', 'FCPP01132', 'Fancy Colors', 'Beige', 88.00, false),
  ('goldline', 'FCPP01133', 'Fancy Colors', 'Light', 88.00, false),
  ('goldline', 'TSP01201', 'Translucent Setting Powder', 'So Natural', 240.00, false),
  ('goldline', 'TSP01202', 'Translucent Setting Powder', 'Ivory Glow', 240.00, true),
  ('goldline', 'TSP01203', 'Translucent Setting Powder', 'Pink Glow', 240.00, false),
  ('goldline', 'TSP01204', 'Translucent Setting Powder', 'Creamy Glow', 240.00, true),
  ('goldline', 'BP01205', 'Bronzing Powder', 'Go Bronze', 200.00, false),
  ('goldline', 'PF09111', 'Powder Plus Foundation', 'Light Natural', 238.00, false),
  ('goldline', 'PF09113', 'Powder Plus Foundation', 'Soft Beige', 238.00, true),
  ('goldline', 'PF09114', 'Powder Plus Foundation', 'Tender Honey', 238.00, true),
  ('goldline', 'PF09115', 'Powder Plus Foundation', 'Medium Tan', 238.00, false),
  ('goldline', 'TWC01151', 'Two Way Cake (21 Grams)', '#1 Light', 185.00, false),
  ('goldline', 'TWC01152', 'Two Way Cake (21 Grams)', '#2 Natural', 185.00, true),
  ('goldline', 'TWC01153', 'Two Way Cake (21 Grams)', '#3 Beige', 185.00, false),
  ('goldline', 'TWC01154', 'Two Way Cake (21 Grams)', '#4 Oriental', 185.00, false),
  ('goldline', 'MTW01171', 'Two Way Cake Matte', 'Matte Natural', 150.00, true),
  ('goldline', 'MTW01172', 'Two Way Cake Matte', 'Matte Ivory', 150.00, false),
  ('goldline', 'MTW01173', 'Two Way Cake Matte', 'Matte Beige', 150.00, false),
  ('goldline', 'MTW01174', 'Two Way Cake Matte', 'Matte Oriental', 150.00, false),
  ('goldline', 'BC01192', 'Beauty Cake', 'Summer Tan', 80.00, false),
  ('goldline', 'BC01194', 'Beauty Cake', 'Amber', 80.00, false),
  ('goldline', 'BC01195', 'Beauty Cake', 'Mocha', 80.00, false),
  ('goldline', 'BC01196', 'Beauty Cake', 'Classic Mint', 80.00, false),
  ('goldline', 'BC01197', 'Beauty Cake', 'Choco Brown', 80.00, false),
  ('goldline', 'CPFCD', 'Cream to Powder Foundation', 'Cookie Dough', 320.00, true),
  ('goldline', 'CPFHO', 'Cream to Powder Foundation', 'Honey Oat', 320.00, false),
  ('goldline', 'CPFB', 'Cream to Powder Foundation', 'Biscuit', 320.00, false),
  ('goldline', 'LQFD091', 'True Colors Liquid Foundation', 'Stay Light', 268.00, false),
  ('goldline', 'LQFD092', 'True Colors Liquid Foundation', 'True Natural', 268.00, false),
  ('goldline', 'BB01L', 'BB Cream', 'BB 01 Light', 238.00, true),
  ('goldline', 'BB02S', 'BB Cream', 'BB 02 Skin', 238.00, false),
  ('goldline', 'BB03N', 'BB Cream', 'BB 03 Natural', 238.00, true),
  ('goldline', 'BB03B', 'BB Cream', 'BB 03 Beige', 238.00, false),
  ('goldline', '6in1PSLFBU', '6 in 1 Perfect Stay Liquid Foundation Infused with Niacinamide', 'Buttermilk', 368.00, true),
  ('goldline', '6in1PSLFC', '6 in 1 Perfect Stay Liquid Foundation Infused with Niacinamide', 'Cashew', 368.00, false),
  ('goldline', '6in1PSLFBE', '6 in 1 Perfect Stay Liquid Foundation Infused with Niacinamide', 'Beige', 368.00, false),
  ('goldline', '6in1PSLFBI', '6 in 1 Perfect Stay Liquid Foundation Infused with Niacinamide', 'Biscotti', 368.00, false),
  ('goldline', 'HSGCC', 'HD Serum Gel Concealer', 'HD Serum Gel Concealer Cashmere', 268.00, false),
  ('goldline', 'HSGCHB', 'HD Serum Gel Concealer', 'HD Serum Gel Concealer Honeybutter', 268.00, true),
  ('goldline', 'HSGCWO', 'HD Serum Gel Concealer', 'HD Serum Gel Concealer Affogato', 268.00, false),
  ('goldline', 'HSGCA', 'HD Serum Gel Concealer', 'HD Serum Gel Concealer Warm Oat', 268.00, false),
  ('goldline', 'CH-001', 'Contour and Highlight Duo Stick', 'Contour and Highlight Duo Stick Medium', 280.00, false),
  ('goldline', 'LMU1451', 'Leg Make-Up', 'Leg Make-up Copper', 80.00, false),
  ('goldline', 'LMU1452', 'Leg Make-Up', 'Leg Make-up Bronze', 80.00, false),
  ('goldline', 'TCES1731', 'True Colors Eye Shadow', 'Eye Shadow Cocoa Pearl', 68.00, false),
  ('goldline', 'TCES1732', 'True Colors Eye Shadow', 'Eye Shadow Bronze Eclaire', 68.00, false),
  ('goldline', 'TCES1733', 'True Colors Eye Shadow', 'Eye Shadow Champagne', 68.00, false),
  ('goldline', 'TCES1734', 'True Colors Eye Shadow', 'Eye Shadow Raisin Wine', 68.00, false),
  ('goldline', 'TCES1735', 'True Colors Eye Shadow', 'Eye Shadow Cool Silver', 68.00, false),
  ('goldline', 'TCES17310', 'True Colors Eye Shadow', 'Eye Shadow Sugar Berry', 68.00, false),
  ('goldline', 'TCES1736', 'True Colors Eye Shadow', 'Eye Shadow Sea Shell', 68.00, false),
  ('goldline', 'TCES1738', 'True Colors Eye Shadow', 'Eye Shadow Gold Foil', 68.00, false),
  ('goldline', 'TCES1739', 'True Colors Eye Shadow', 'Eye Shadow Carribean Blue', 68.00, false),
  ('goldline', 'TCES17311', 'True Colors Eye Shadow', 'Eye Shadow Caramel', 68.00, false),
  ('goldline', 'TCES17312', 'True Colors Eye Shadow', 'Eye Shadow Snow', 68.00, false),
  ('goldline', 'TCES17313', 'True Colors Eye Shadow', 'Eye Shadow Gold Frost', 68.00, false),
  ('goldline', 'TCES17314', 'True Colors Eye Shadow', 'Eye Shadow Soft Black', 68.00, false),
  ('goldline', 'TCES17316', 'True Colors Eye Shadow', 'Eye Shadow Iced Violet', 68.00, false),
  ('goldline', 'TCES17317', 'True Colors Eye Shadow', 'Eye Shadow Electric Pink', 68.00, false),
  ('goldline', 'TCPBPP01', 'True Colors Powder Blush', 'Powder Blush Peach Pop', 160.00, false),
  ('goldline', 'TCPBT02', 'True Colors Powder Blush', 'Powder Blush Tomato', 160.00, true),
  ('goldline', 'TCPBSM03', 'True Colors Powder Blush', 'Powder Blush Sugar Maple', 160.00, true),
  ('goldline', 'TCPBCR04', 'True Colors Powder Blush', 'Powder Blush Cool Rum', 160.00, true),
  ('goldline', 'TCPBSM05', 'True Colors Powder Blush', 'Powder Blush Strawberry Milk', 160.00, false),
  ('goldline', 'TCPBPL06', 'True Colors Powder Blush', 'Powder Blush Pink Cola', 160.00, false),
  ('goldline', 'TCPBGP07', 'True Colors Powder Blush', 'Powder Blush Guava Punch', 160.00, true),
  ('goldline', 'TCPBVB08', 'True Colors Powder Blush', 'Powder Blush Verry Berry', 160.00, false),
  ('goldline', 'CDSBLB01', 'Cloud Drops Soft Blur Liquid Blush', 'Liquid Blush Petal Talk', 299.00, true),
  ('goldline', 'CDSBLB02', 'Cloud Drops Soft Blur Liquid Blush', 'Liquid Blush Bloom Bouquet', 299.00, true),
  ('goldline', 'CDSBLB03', 'Cloud Drops Soft Blur Liquid Blush', 'Liquid Blush Poppy Pink', 299.00, false),
  ('goldline', 'CDSBLB04', 'Cloud Drops Soft Blur Liquid Blush', 'Liquid Blush Tease Me', 299.00, true),
  ('goldline', 'CDSBLB05', 'Cloud Drops Soft Blur Liquid Blush', 'Liquid Blush Hush Blush', 299.00, false),
  ('goldline', 'CDSBLB06', 'Cloud Drops Soft Blur Liquid Blush', 'Liquid Blush Love Cake', 299.00, false),
  ('goldline', 'MS09113', 'Make-Up Collection', 'Bare Basic Palette', 168.00, false),
  ('goldline', 'MS099717', 'Make-Up Collection', 'Naturally Beautiful Palette', 188.00, false),
  ('goldline', 'MUIS09', 'Make-Up Collection', 'TCC In Style Make-up Palette', 288.00, false),
  ('goldline', 'MUMBS02', 'Make-Up Collection', 'Bombshell Eyeshadow Palette', 225.00, false),
  ('goldline', 'MUO03', 'Make-Up Collection', 'Obsession Eyeshadow Palette', 225.00, false),
  ('goldline', 'MUBBEP', 'Make-Up Collection', 'Berry Blossom Eyeshadow Palette', 225.00, false),
  ('goldline', 'MUSEP', 'Make-Up Collection', 'Sakura Eyeshadow Palette', 225.00, false),
  ('goldline', 'BESP', 'Make-Up Collection', 'Bejeweled Eyeshadow Palette', 320.00, false),
  ('goldline', 'LSESP', 'Make-Up Collection', 'Love Spells Eyeshadow Palette', 320.00, false),
  ('goldline', 'CPC001', 'Make-Up Collection', 'Contour Palette', 350.00, false),
  ('goldline', 'USMLLC01', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color O So Spice', 225.00, true),
  ('goldline', 'USMLLC02', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Fast Play', 225.00, false),
  ('goldline', 'USMLLC03', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Simply Nude', 225.00, true),
  ('goldline', 'USMLLC04', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Bespoke', 225.00, false),
  ('goldline', 'USMLLC05', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Dirty Talk', 225.00, false),
  ('goldline', 'USMLLC06', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Chic Cafe', 225.00, false),
  ('goldline', 'USMLLC07', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Chill Pill', 225.00, true),
  ('goldline', 'USMLLC08', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Iconic Red', 225.00, false),
  ('goldline', 'USMLLC09', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Catwalk', 225.00, false),
  ('goldline', 'USMLLC10', 'Ultra Stay Matte Liquid Lip Color', 'Matte Lip Color Smitten', 225.00, false),
  ('goldline', 'MPMLSCB01', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Goddess', 250.00, false),
  ('goldline', 'MPMLSCB02', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Kiss Of An Angel', 250.00, true),
  ('goldline', 'MPMLSCB03', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Heart to Heart', 250.00, true),
  ('goldline', 'MPMLSCB04', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Adore You', 250.00, false),
  ('goldline', 'MPMLSCB05', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Love On Fire', 250.00, true),
  ('goldline', 'MPMLSCB08', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Euphoria', 250.00, false),
  ('goldline', 'MPMLSCB09', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Hot Red', 250.00, true),
  ('goldline', 'MPMLSCB10', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick High Spirits', 250.00, false),
  ('goldline', 'MPMLSCB11', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Sweet Marsala', 250.00, true),
  ('goldline', 'MPMLSCB12', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Wine Soiree', 250.00, false),
  ('goldline', 'MPMLSCB13', 'Mineral Powder Matte Lipstick with Collagen Booster', 'Matte Lipstick Malibu', 250.00, false),
  ('goldline', 'IPSLS01', 'Icy Pout Serum Lip Stain', 'Lip Stain Caramel Swirl', 285.00, true),
  ('goldline', 'IPSLS02', 'Icy Pout Serum Lip Stain', 'Lip Stain Honey Waffle', 285.00, false),
  ('goldline', 'IPSLS03', 'Icy Pout Serum Lip Stain', 'Lip Stain Pumpkin Pie', 285.00, true),
  ('goldline', 'IPSLS04', 'Icy Pout Serum Lip Stain', 'Lip Stain Pink Lemonade', 285.00, true),
  ('goldline', 'IPSLS05', 'Icy Pout Serum Lip Stain', 'Lip Stain Spiced Candy', 285.00, false),
  ('goldline', 'IPSLS06', 'Icy Pout Serum Lip Stain', 'Lip Stain Sparkling Rose', 285.00, false),
  ('goldline', 'IPSLS07', 'Icy Pout Serum Lip Stain', 'Lip Stain Cherry Fizz', 285.00, true),
  ('goldline', 'IPSLS08', 'Icy Pout Serum Lip Stain', 'Lip Stain Frozen Berry', 285.00, false),
  ('goldline', 'IPSLS09', 'Icy Pout Serum Lip Stain', 'Lip Stain Iced Praline', 285.00, false),
  ('goldline', 'RELB2011', 'Eye Pencil w/ Brush (Retractable)', 'Eye Pencil Retractable Dark Brown', 80.00, false),
  ('goldline', 'RELB2012', 'Eye Pencil w/ Brush (Retractable)', 'Eye Pencil Retractable Black', 80.00, false),
  ('goldline', 'EPWB01', 'Eye Pencil w/ Brush (Plastic)', 'Eye Pencil Plastic Dark Brown', 80.00, false),
  ('goldline', 'EPWB02', 'Eye Pencil w/ Brush (Plastic)', 'Eye Pencil Plastic Black', 80.00, false),
  ('goldline', 'BPDB01', 'Brow Pencil (Paraben Free)', 'Brow Pencil Dark Brown', 80.00, true),
  ('goldline', 'BPFB02', 'Brow Pencil (Paraben Free)', 'Brow Pencil Fudge Brown', 80.00, false),
  ('goldline', 'BPCB03', 'Brow Pencil (Paraben Free)', 'Brow Pencil Coco Brown', 80.00, false),
  ('goldline', 'KPMNEP99', 'Mineral Kohl - Onyx', 'Mineral Kohl Onyx', 150.00, false),
  ('goldline', 'BMEPC01', 'Brow Master Eye Pencil', 'Brow Master Cocoa', 175.00, false),
  ('goldline', 'BMEPP02', 'Brow Master Eye Pencil', 'Brow Master Pecan', 175.00, true),
  ('goldline', 'BMEPG03', 'Brow Master Eye Pencil', 'Brow Master Gingerbread', 175.00, false),
  ('goldline', 'BMEPM04', 'Brow Master Eye Pencil', 'Brow Master Macadamia', 175.00, true),
  ('goldline', 'BMEPBS05', 'Brow Master Eye Pencil', 'Brow Master Brown Sugar', 175.00, false),
  ('goldline', 'PEP091', 'Professional Eye Pencil', 'Professional Eye Pencil 801 Black Brown', 120.00, true),
  ('goldline', 'PEP092', 'Professional Eye Pencil', 'Professional Eye Pencil 802 Medium Brown', 120.00, true),
  ('goldline', 'PEP093', 'Professional Eye Pencil', 'Professional Eye Pencil 803 Brown', 120.00, false),
  ('goldline', 'PLP092', 'Professional Lip Pencil', 'Professional Lip Pencil LP02 Rose Berry', 120.00, true),
  ('goldline', 'PLP093', 'Professional Lip Pencil', 'Professional Lip Pencil LP03 Blaze', 120.00, false),
  ('goldline', 'PLP094', 'Professional Lip Pencil', 'Professional Lip Pencil LP04 Rosette', 120.00, true),
  ('goldline', 'PLP095', 'Professional Lip Pencil', 'Professional Lip Pencil LP05 Spice', 120.00, false),
  ('goldline', 'PLP096', 'Professional Lip Pencil', 'Professional Lip Pencil LP06 Coral Rust', 120.00, false),
  ('goldline', 'ECPS091', 'Eye Contour Pencil w/ Smudger', 'Eye Contour Pencil Blackest Black', 100.00, false),
  ('goldline', 'ECPS092', 'Eye Contour Pencil w/ Smudger', 'Eye Contour Pencil Deep Blonde', 100.00, false),
  ('goldline', 'GEP091', 'Gorgeous Eye Pencil w/ Smudger', 'Gorgeous Eye Pencil Bronze Glow', 100.00, false),
  ('goldline', 'GEP094', 'Gorgeous Eye Pencil w/ Smudger', 'Gorgeous Eye Pencil Nice Gal', 100.00, true),
  ('goldline', 'GEP095', 'Gorgeous Eye Pencil w/ Smudger', 'Gorgeous Eye Pencil Pink Diamond', 100.00, false),
  ('goldline', 'CIEP99VT', 'Color Intense Eye Pencil', 'Color Intense Eye Pencil Vivid Turquoise', 100.00, false),
  ('goldline', 'MPEPTE', 'Minerals Precise Eye Pencil', 'Minerals Precise Eye Pencil Tiger Eye', 175.00, false),
  ('goldline', 'MPEPC', 'Minerals Precise Eye Pencil', 'Minerals Precise Eye Pencil Chestnut', 175.00, true),
  ('goldline', 'MPEPIB', 'Minerals Precise Eye Pencil', 'Minerals Precise Eye Pencil Intense Bronze', 175.00, false),
  ('goldline', 'MPEPH', 'Minerals Precise Eye Pencil', 'Minerals Precise Eye Pencil Hazelnut', 175.00, true),
  ('goldline', 'MPEPW', 'Minerals Precise Eye Pencil', 'Minerals Precise Eye Pencil Walnut', 175.00, false),
  ('goldline', 'MPEPT', 'Minerals Precise Eye Pencil', 'Minerals Precise Eye Pencil Taupe', 175.00, false),
  ('goldline', 'MPEPTR', 'Minerals Precise Eye Pencil', 'Minerals Precise Eye Pencil Truffle', 175.00, true),
  ('goldline', 'MPEPTN', 'Minerals Precise Eye Pencil', 'Minerals Precise Eye Pencil Toffee Nut', 175.00, false),
  ('goldline', 'MSCOL', 'Multi Stick with Collagen Booster', 'Multi Stick Oh Lala', 288.00, false),
  ('goldline', 'MSCA', 'Multi Stick with Collagen Booster', 'Multi Stick Amore', 288.00, false),
  ('goldline', 'MSCPR', 'Multi Stick with Collagen Booster', 'Multi Stick Pink Rush', 288.00, false),
  ('goldline', 'LCTPFCB', 'Lip and Cheek Tint Paraben-Free', 'Lip and Cheek Tint Cheeky Blush', 125.00, true),
  ('goldline', 'LCTPFPOP', 'Lip and Cheek Tint Paraben-Free', 'Lip and Cheek Tint Pinch O Pink', 125.00, true),
  ('goldline', 'LCTPFBG', 'Lip and Cheek Tint Paraben-Free', 'Lip and Cheek Tint Beach Glow', 125.00, false),
  ('goldline', 'CEB091', 'Eyebrow Liner Duo Kit', 'Eyebrow Liner Duo Coffee / Black', 238.00, false),
  ('goldline', 'CEB092', 'Eyebrow Liner Duo Kit', 'Eyebrow Liner Duo Coffee / Latte', 238.00, false),
  ('goldline', '24/7SEPMM', '24/7 Stylo Eyeliner Pen', 'Stylo Eyeliner Pen Midnight Matte', 248.00, false),
  ('goldline', '24/7SEPUM', '24/7 Stylo Eyeliner Pen', 'Stylo Eyeliner Pen Umber Matte', 248.00, false),
  ('goldline', 'EGLE', 'Easy Glide Liquid Eyeliner', 'Easy Glide Liquid Eyeliner Black', 168.00, false),
  ('goldline', 'TBGB02', 'Tinted Brow Gel', 'Tinted Brow Gel Brunette', 238.00, true),
  ('goldline', 'TBGAB03', 'Tinted Brow Gel', 'Tinted Brow Gel Ash Blonde', 238.00, false),
  ('goldline', 'TBGE04', 'Tinted Brow Gel', 'Tinted Brow Gel Espresso', 238.00, false),
  ('goldline', 'CMS091', 'Eyebrow Gel', 'Eyebrow Gel Clear Mascara', 120.00, false),
  ('goldline', 'LCMS01', 'Length & Curl Mascara', 'Length and Curl Mascara', 198.00, false),
  ('goldline', 'ELDF01', 'Eyelash Defining Mascara', 'Eyelash Defining Mascara Black', 130.00, true),
  ('goldline', 'ELDF03', 'Eyelash Defining Mascara', 'Eyelash Defining Mascara Brown', 130.00, false),
  ('goldline', 'CELMS1', 'Color Eyes Lengthening Mascara', 'Color Eyes Lengthening Mascara', 188.00, false),
  ('goldline', 'CEVMS1', 'Color Eyes Volume Mascara', 'Color Eyes Volume Mascara', 188.00, false),
  ('goldline', 'CEEMS1', 'Color Eyes Eyeliner Plus Mascara', 'Color Eyes Eyeliner Plus Mascara', 168.00, false),
  ('goldline', '7XMSCR', '7X Volume Curl Mascara', '7X Volume Curl Mascara', 288.00, false),
  ('goldline', 'MUSS', 'Make-Up Setting Spray', 'Make-up Setting Spray', 288.00, false),
  ('goldline', 'SOLMWB', 'Skin+Overnight Lip Mask', 'Overnight Lip Mask Wild Berry', 236.00, false),
  ('goldline', 'HBP', 'Hydro Blurring Primer', 'Hydro Blurring Primer', 375.00, false),
  ('goldline', 'SPG0161', 'Accessories', 'Beauty Sponge Big Yellow', 60.00, false),
  ('goldline', 'PPF163', 'Accessories', 'Powder Puff', 32.00, false),
  ('goldline', 'BLSPG162', 'Accessories', 'Latex Sponge Square Korea', 60.00, false),
  ('goldline', 'RLSPG162', 'Accessories', 'Round Latex Sponge Korea', 60.00, false),
  ('goldline', 'WSP208', 'Accessories', 'Wedge Sponge 2pcs', 40.00, false),
  ('goldline', '3D-TSB16', 'Accessories', 'Blending Sponge Oval', 250.00, false),
  ('goldline', 'PROEC08', 'Accessories', 'Professional Eyelash Curler', 188.00, false),
  ('goldline', 'PROLP08', 'Accessories', 'Lashpad', 75.00, false),
  ('goldline', 'CS0164', 'Accessories', 'Curler Silver White Rubber', 100.00, false),
  ('goldline', 'SCR166', 'Accessories', 'Metal Curler Rubber Refill', 45.00, false),
  ('goldline', 'EXT193', 'Accessories', 'Extractor Pimple Pick', 88.00, false),
  ('goldline', 'TZ0168', 'Accessories', 'Twissor Scissor Type', 60.00, false),
  ('goldline', 'TZ0169', 'Accessories', 'Tweezer', 60.00, false),
  ('goldline', 'TZGL08', 'Accessories', 'Gold Tweezer', 88.00, false),
  ('goldline', 'ELB160', 'Accessories', 'Eyebrow Shaver Korea', 50.00, false),
  ('goldline', 'SHS170', 'Accessories', 'Sharpener Single', 50.00, false),
  ('goldline', 'EPS001', 'Accessories', 'Professional Lip and Eye Sharpener Single', 120.00, false),
  ('goldline', 'NCSIL8', 'Accessories', 'Nail Cutter', 50.00, false),
  ('goldline', 'SSCR218', 'Accessories', 'Safety Scissor', 120.00, false),
  ('goldline', 'EARCL8', 'Accessories', 'Ear Cleaner', 45.00, false),
  ('goldline', 'PKB', 'Accessories', 'Professional Kabuki Brush', 238.00, false),
  ('goldline', 'RLBP191', 'Accessories', 'Ret Lip Brush Aluminum Pink or Violet', 60.00, false),
  ('goldline', 'RLBS191', 'Accessories', 'Ret Lip Brush Aluminum Silver', 60.00, false),
  ('goldline', 'LPDP0121', 'Accessories', 'Loose Powder Case Pink', 80.00, false),
  ('goldline', 'LPDB0121', 'Accessories', 'Loose Powder Case Blue', 80.00, false),
  ('goldline', 'EBWC08', 'Accessories', 'Eyebrow Brush w Cap Violet', 45.00, false),
  ('goldline', 'LBWC08', 'Accessories', 'Lip Brush w Cap Pink', 45.00, false),
  ('goldline', 'ACCS03', 'Accessories', 'Oval Paddle Brush #03 Small', 150.00, false),
  ('goldline', 'ACCS05', 'Accessories', 'Oval Paddle Brush #05 Big', 180.00, false),
  ('goldline', 'ACCS185', 'Accessories', 'Stippling Brush #185', 288.00, false),
  ('goldline', 'ACCS193', 'Accessories', 'Foundation Brush #193', 288.00, false),
  ('goldline', 'ACCS181', 'Accessories', 'Powder Brush #181', 288.00, false),
  ('goldline', 'ACCS191', 'Accessories', 'Powder Blush Brush #191', 288.00, false),
  ('goldline', 'ACCS521', 'Accessories', 'Retractable Powder Brush #521', 238.00, false),
  ('goldline', 'ACCS183', 'Accessories', 'Slanted Blusher Brush #183', 188.00, false),
  ('goldline', 'ACCS525', 'Accessories', 'Retractable Blusher Brush #525', 140.00, false),
  ('goldline', 'ACCS277', 'Accessories', 'Lip Brush #277', 168.00, false),
  ('goldline', 'ACCS233', 'Accessories', 'Eye Shader Brush #233', 150.00, false),
  ('goldline', 'ACCS251', 'Accessories', 'Angled Eyebrow Brush #251', 150.00, false),
  ('goldline', 'ACCS255', 'Accessories', 'Eyebrow Lash Brush with Comb #255', 150.00, false),
  ('goldline', 'ACCS231', 'Accessories', 'Angled Shading Brush #231', 125.00, false),
  ('goldline', 'ACCS235', 'Accessories', 'Blending Brush #235', 125.00, false),
  ('goldline', 'ACCS237', 'Accessories', 'Eyeliner Brush #237', 125.00, false),
  ('goldline', 'ACCS253', 'Accessories', 'Mascara Brush #253', 125.00, false),
  ('goldline', '2IN1EBBD25', 'Accessories', '2-in-1 Eyebrow Brush D25', 150.00, false),
  ('goldline', '2IN1ESBD28', 'Accessories', '2-in-1 Eyeshadow Brush D28', 150.00, false),
  ('goldline', 'RLBD278', 'Accessories', 'Retractable Lip Brush D278', 136.00, false),
  ('goldline', 'AEBBCD235', 'Accessories', 'Angled Eyebrow Brush with Cap D235', 75.00, false),
  ('goldline', 'ACCSBELTBAG', 'Accessories', 'Belt Bag', 600.00, false),
  ('goldline', 'ACCS197', 'Accessories', 'Flat Brush #197', 288.00, false),
  ('goldline', 'TLEA09', 'Accessories', 'Eyelash Adhesive', 60.00, false),
  ('goldline', 'FELA', 'Accessories', 'False Eyelash Applicator', 180.00, false),
  ('goldline', 'SSDEEP', 'Accessories', 'Soft Silicone Dual End Ear Pick', 140.00, false),
  ('goldline', 'TLDL6619', 'Trulashes - De Luxe', 'Trulashes De Luxe 86619', 130.00, false),
  ('goldline', 'TLDL4474', 'Trulashes - De Luxe', 'Trulashes De Luxe 84474', 130.00, false),
  ('goldline', 'TLDL5295', 'Trulashes - De Luxe', 'Trulashes De Luxe 85295', 130.00, false),
  ('goldline', 'TLDL6617', 'Trulashes - De Luxe', 'Trulashes De Luxe 86617', 130.00, false),
  ('goldline', 'TLDL7035', 'Trulashes - De Luxe', 'Trulashes De Luxe 87035', 130.00, false),
  ('goldline', 'TLDL5255', 'Trulashes - De Luxe', 'Trulashes De Luxe 85255', 130.00, false),
  ('goldline', 'TLGL4331B', 'Trulashes - Glamour Lashes', 'Glamour Lashes 84331 brown', 150.00, false),
  ('goldline', 'TLGL4552', 'Trulashes - Glamour Lashes', 'Glamour Lashes 84552', 150.00, false),
  ('goldline', 'TLGL4452', 'Trulashes - Glamour Lashes', 'Glamour Lashes 84452', 150.00, false),
  ('goldline', 'TLGL4440', 'Trulashes - Glamour Lashes', 'Glamour Lashes 84440', 150.00, false),
  ('goldline', 'TLGL4453', 'Trulashes - Glamour Lashes', 'Glamour Lashes 84453', 150.00, false),
  ('goldline', 'TLGL4469', 'Trulashes - Glamour Lashes', 'Glamour Lashes 84469', 150.00, false),
  ('goldline', 'TLGL4711', 'Trulashes - Glamour Lashes', 'Glamour Lashes 84711', 150.00, false),
  ('goldline', 'TLGL5268', 'Trulashes - Glamour Lashes', 'Glamour Lashes 85268', 150.00, false),
  ('goldline', 'EDNH4525', 'Elise Diva Lashes - Natural Hair', 'Elise Diva Lashes L4525', 198.00, false),
  ('goldline', 'EDNH4526', 'Elise Diva Lashes - Natural Hair', 'Elise Diva Lashes L4526', 198.00, false),
  ('goldline', 'EDNH4289', 'Elise Diva Lashes - Natural Hair', 'Elise Diva Lashes X4289', 198.00, false),
  ('goldline', 'EDNH4291', 'Elise Diva Lashes - Natural Hair', 'Elise Diva Lashes L4291', 198.00, false),
  ('goldline', 'EDNH5127', 'Elise Diva Lashes - Natural Hair', 'Elise Diva Lashes XL5127', 198.00, false),
  ('goldline', 'EDNH4312', 'Elise Diva Lashes - Natural Hair', 'Elise Diva Lashes N4312', 198.00, false),
  ('goldline', 'EDNH7464', 'Elise Diva Lashes - Natural Hair', 'Elise Diva Lashes DW7464', 198.00, false),
  ('goldline', 'EDNH7927', 'Elise Diva Lashes - Natural Hair', 'Elise Diva Lashes C7927', 198.00, false),
  ('goldline', 'ELN4455', 'Elise Lashes', 'Elise Lashes N4455', 238.00, false),
  ('goldline', 'ELCX1313', 'Elise Lashes', 'Elise Lashes CX1313', 238.00, false),
  ('goldline', 'ELI8089', 'Elise Lashes', 'Elise Lashes I8089', 238.00, false),
  ('goldline', 'ELF8058', 'Elise Lashes', 'Elise Lashes F8058', 238.00, false),
  ('goldline', 'EFLLF11', 'Elise Feather Lite Lashes', 'Elise Feather Lite Lashes F11', 198.00, false),
  ('goldline', 'EFLLF12', 'Elise Feather Lite Lashes', 'Elise Feather Lite Lashes F12', 198.00, false),
  ('goldline', 'EFLLF13', 'Elise Feather Lite Lashes', 'Elise Feather Lite Lashes F13', 198.00, false),
  ('goldline', 'EFLLF14', 'Elise Feather Lite Lashes', 'Elise Feather Lite Lashes F14', 198.00, false),
  ('goldline', 'JLLS04', 'Juicy Lips Lipstick', 'Juicy Lips Lipstick Pink Champagne', 88.00, false)
on conflict (company_id, item_code) do update set
  product_line  = excluded.product_line,
  variant       = excluded.variant,
  unit_price    = excluded.unit_price,
  is_bestseller = excluded.is_bestseller;
