#!/usr/bin/env bash
# LOCAL ONLY. A throwaway Supabase-compatible stack for end-to-end tests: a real Postgres + a real PostgREST, reached by
# supabase-js through a tiny loopback proxy exactly like a hosted project.
#   scripts/local-supabase/up.sh            create (or reuse) the network, containers and proxy, then apply the SQL
#   scripts/local-supabase/up.sh --reapply  re-run ONLY the SQL files against the running stack
#   scripts/local-supabase/up.sh --explore  (alone or with --reapply) ALSO build the Ask Coop Explore data layer: the booth-lead tables,
#                                           scripts/coop-explore-fixture.sql (fictional rows with deliberate traps), supabase/coop_chat_explore.sql
#                                           (role coop_explore_ro + fifteen views), supabase/coop_chat_explore_direct.sql
#                                           (direct reads: grants, trigger, cron) and scripts/coop-direct-fixture.sql (secret and tenant traps), its password, and print supabase/coop_chat_explore_direct_checks.sql
#                                           (the direct-read state; coop_chat_explore_checks.sql is for the Train 1 state only)
# Uses only the cached images (nothing is pulled), its own network `coop-local`, containers `coop-local-db` (127.0.0.1:54421)
# and `coop-local-rest` (127.0.0.1:54423), and the proxy on 127.0.0.1:54420. No volume: scripts/local-supabase/down.sh = clean slate.
# Secrets are generated on first run into the gitignored scripts/local-supabase/.local-env and never printed.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
ENVF="$HERE/.local-env"
NET=coop-local DB=coop-local-db REST=coop-local-rest
DB_IMAGE=public.ecr.aws/supabase/postgres:17.11.0.002
REST_IMAGE=public.ecr.aws/supabase/postgrest:v16.4
PROXY_PORT=54420 DB_PORT=54421 REST_PORT=54423
URL="http://127.0.0.1:${PROXY_PORT}"

die() { echo "up.sh: $*" >&2; exit 1; }
running() { [ "$(docker inspect -f '{{.State.Running}}' "$1" 2>/dev/null || echo false)" = "true" ]; }
exists() { docker inspect "$1" >/dev/null 2>&1; }
mine() { [ "$(docker inspect -f '{{ index .Config.Labels "coop-local" }}' "$1" 2>/dev/null)" = "1" ]; }
psql_pg() { docker exec -i "$DB" psql -h 127.0.0.1 -U postgres -d postgres -v ON_ERROR_STOP=1 -q "$@"; }

command -v docker >/dev/null || die 'docker is not installed'
command -v node >/dev/null || die 'node is not installed'

# ---- secrets (first run only) ---------------------------------------------------------------------------------------
if [ ! -f "$ENVF" ]; then
  if exists "$DB" || exists "$REST"; then die "containers exist but $ENVF is missing: run scripts/local-supabase/down.sh first"; fi
  node -e '
    const {randomBytes, createHmac} = require("node:crypto");
    const secret = randomBytes(32).toString("hex");
    const pg = randomBytes(16).toString("hex");
    const b = (o) => Buffer.from(JSON.stringify(o)).toString("base64url");
    const now = Math.floor(Date.now() / 1000);
    const body = b({alg: "HS256", typ: "JWT"}) + "." + b({role: "service_role", iss: "supabase", iat: now, exp: now + 3 * 365 * 86400});
    const key = body + "." + createHmac("sha256", secret).update(body).digest("base64url");
    const lines = [
      "# LOCAL ONLY. Generated by scripts/local-supabase/up.sh. Gitignored. Never use these against a hosted project.",
      "SUPABASE_URL_ARCHIVE=" + process.argv[1],
      "SUPABASE_SERVICE_ROLE_KEY_ARCHIVE=" + key,
      "CHAT_RO_JWT_SECRET=" + secret,
      "# For test/chat-ro-local.integration.test.ts and scripts/coop-chat-ro-proof.mjs",
      "SB_LOCAL_URL=" + process.argv[1],
      "SB_LOCAL_JWT_SECRET=" + secret,
      "SB_URL=" + process.argv[1],
      "SB_JWT_SECRET=" + secret,
      "SB_PSQL_CMD=\"docker exec -i coop-local-db psql -h 127.0.0.1 -U postgres -d postgres -v ON_ERROR_STOP=1\"",
      "# Used by up.sh only",
      "LOCAL_PG_PASSWORD=" + pg,
    ];
    require("node:fs").writeFileSync(process.argv[2], lines.join("\n") + "\n", {mode: 0o600});
  ' "$URL" "$ENVF"
  echo "generated $ENVF (not printed)"
fi
chmod 600 "$ENVF"
# shellcheck disable=SC1090
set -a; . "$ENVF"; set +a
# Safety: this stack is loopback only. Refuse anything else, whatever the file says.
case "$SUPABASE_URL_ARCHIVE" in http://127.0.0.1:*|http://localhost:*) ;; *) die "refusing: SUPABASE_URL_ARCHIVE in $ENVF is not a loopback URL" ;; esac

# ---- Explore mode secrets (first --explore run only): a password for coop_explore_ro, and the env the app needs ----------------------
EXPLORE=${EXPLORE:-0}
for arg in "$@"; do if [ "$arg" = "--explore" ]; then EXPLORE=1; fi; done
if [ "$EXPLORE" = "1" ] && ! grep -q '^EXPLORE_PG_PASSWORD=' "$ENVF"; then
  EXPLORE_PG_PASSWORD="$(node -e 'process.stdout.write(require("node:crypto").randomBytes(24).toString("hex"))')"
  {
    echo "# Explore mode (Ask Coop run_query). LOCAL ONLY. Generated by up.sh --explore."
    echo "EXPLORE_PG_PASSWORD=${EXPLORE_PG_PASSWORD}"
    echo "EXPLORE_DATABASE_URL=postgres://coop_explore_ro:${EXPLORE_PG_PASSWORD}@127.0.0.1:${DB_PORT}/postgres"
    echo "EXPLORE_MODE=on"
    echo "EXPLORE_ALLOWED_EMAILS=dev@localhost"
    echo "ALLOWED_EMAILS=dev@localhost"
  } >> "$ENVF"
  echo "added the Explore variables to $ENVF (not printed)"
fi
# shellcheck disable=SC1090
set -a; . "$ENVF"; set +a

# ---- the SQL, in order ----------------------------------------------------------------------------------------------
PRE_DROP_VIEWS="pos_orders_completed coop_explore_orders coop_explore_order_items coop_explore_products coop_explore_bundles coop_explore_bundle_items coop_explore_events coop_explore_prices coop_explore_price_changes coop_explore_event_leads coop_explore_digest coop_explore_inventory coop_explore_inventory_by_location coop_explore_inventory_lots coop_explore_stock_movements coop_explore_stock_event"

apply_sql() {
  local f out v
  # The explore views and pos_orders_completed depend on the pos_* tables, which scripts/coop-chat-ro-fixture.sql drops and recreates: drop them first (harmless if absent).
  for v in $PRE_DROP_VIEWS; do psql_pg -o /dev/null -c "set client_min_messages = warning; drop view if exists public.$v" || die "could not drop $v"; done
  for f in scripts/coop-chat-ro-fixture.sql scripts/coop-stock-fixture.sql scripts/local-supabase/seed-digest.sql supabase/coop_chat_readonly.sql supabase/coop_chat_digest.sql supabase/coop_chat_stock.sql supabase/coop_reports.sql; do
    if [ ! -f "$ROOT/$f" ]; then echo "skipped $f (not found yet; run scripts/local-supabase/up.sh --reapply once it exists)"; continue; fi
    out="$(psql_pg -o /dev/null < "$ROOT/$f" 2>&1)" || { echo "$out" | grep -v '^NOTICE:' >&2; die "failed applying $f"; }
    echo "applied $f"
  done
  if [ "$EXPLORE" = "1" ]; then apply_explore; fi
  psql_pg -o /dev/null -c "notify pgrst, 'reload config'; notify pgrst, 'reload schema';"
  sleep 2
}

apply_explore() {
  local f out
  [ -n "${EXPLORE_PG_PASSWORD:-}" ] || die 'EXPLORE_PG_PASSWORD is not in .local-env'
  for f in supabase/spin_wheel_leads.sql supabase/spin_wheel_leads_instagram.sql scripts/coop-explore-fixture.sql supabase/coop_chat_explore.sql supabase/coop_chat_explore_direct.sql supabase/coop_chat_default_views.sql scripts/coop-direct-fixture.sql; do
    out="$(psql_pg -o /dev/null < "$ROOT/$f" 2>&1)" || { echo "$out" | grep -v '^NOTICE:' >&2; die "failed applying $f"; }
    echo "applied $f"
    # direct reads: say whether the event trigger and the cron guard were installed (the file never fails on either)
    echo "$out" | grep -E '^NOTICE: +(event trigger (coop|NOT)|pg_cron (job|is|could))' | sed 's/^NOTICE: */  /' || true
  done
  # the password is a hex string from .local-env: safe to inline, never printed
  psql_pg -o /dev/null -c "alter role coop_explore_ro with password '${EXPLORE_PG_PASSWORD}'" || die 'could not set the coop_explore_ro password'
  # the direct-read state: coop_chat_explore_checks.sql describes the Train 1 state only and would read BAD here by design
  echo '--- supabase/coop_chat_explore_direct_checks.sql (read the output: see the expected result above each query) ---'
  psql_pg -P pager=off < "$ROOT/supabase/coop_chat_explore_direct_checks.sql" || die 'the checks failed to run'
}

REAPPLY=0
for arg in "$@"; do
  case "$arg" in
    --reapply) REAPPLY=1 ;;
    --explore) EXPLORE=1 ;;
    *) die "unknown argument $arg (only --reapply and --explore)" ;;
  esac
done
if [ "$REAPPLY" = "1" ]; then
  running "$DB" || die 'the database container is not running: run scripts/local-supabase/up.sh first'
  apply_sql
  exit 0
fi

# ---- images, network, containers ------------------------------------------------------------------------------------
for img in "$DB_IMAGE" "$REST_IMAGE"; do docker image inspect "$img" >/dev/null 2>&1 || die "image $img is not cached locally (this script never pulls)"; done

if docker network inspect "$NET" >/dev/null 2>&1; then
  [ "$(docker network inspect -f '{{ index .Labels "coop-local" }}' "$NET")" = "1" ] || die "a network named $NET exists that this script did not create"
else
  docker network create --label coop-local=1 "$NET" >/dev/null
fi

if exists "$DB"; then
  mine "$DB" || die "a container named $DB exists that this script did not create"
  running "$DB" || docker start "$DB" >/dev/null
else
  docker run -d --name "$DB" --label coop-local=1 --network "$NET" -p "127.0.0.1:${DB_PORT}:5432" \
    -e POSTGRES_PASSWORD="$LOCAL_PG_PASSWORD" "$DB_IMAGE" >/dev/null
fi

echo -n 'waiting for postgres'
for _ in $(seq 1 90); do
  if docker exec "$DB" psql -h 127.0.0.1 -U postgres -d postgres -tAc "select 1 from pg_roles where rolname = 'authenticator'" 2>/dev/null | grep -q 1; then break; fi
  echo -n .; sleep 2
done
echo
docker exec "$DB" psql -h 127.0.0.1 -U postgres -d postgres -tAc 'select 1' >/dev/null 2>&1 || die 'postgres did not become ready (docker logs coop-local-db)'

# PostgREST connects as `authenticator`. The image creates the role (and anon, authenticated, service_role) but does
# not tie its password to POSTGRES_PASSWORD, so set it here (a hex string, safe to inline; never printed).
docker exec -i "$DB" psql -h 127.0.0.1 -U supabase_admin -d postgres -v ON_ERROR_STOP=1 -q -o /dev/null \
  -c "alter role authenticator with password '${LOCAL_PG_PASSWORD}'" || die 'could not set the authenticator password'
if exists "$REST"; then
  mine "$REST" || die "a container named $REST exists that this script did not create"
  running "$REST" || docker start "$REST" >/dev/null
else
  docker run -d --name "$REST" --label coop-local=1 --network "$NET" -p "127.0.0.1:${REST_PORT}:3000" \
    -e PGRST_DB_URI="postgres://authenticator:${LOCAL_PG_PASSWORD}@${DB}:5432/postgres" \
    -e PGRST_DB_SCHEMAS=public -e PGRST_DB_ANON_ROLE=anon -e PGRST_JWT_SECRET="$CHAT_RO_JWT_SECRET" \
    -e PGRST_DB_MAX_ROWS=1000 -e PGRST_SERVER_HOST=0.0.0.0 "$REST_IMAGE" >/dev/null
fi

# ---- the proxy (host process, loopback only) ------------------------------------------------------------------------
PIDF="$HERE/.proxy.pid"
if [ -f "$PIDF" ] && ps -p "$(cat "$PIDF")" -o command= 2>/dev/null | grep -q 'local-supabase/proxy.mjs'; then
  :
else
  if lsof -nP -iTCP:"$PROXY_PORT" -sTCP:LISTEN >/dev/null 2>&1; then die "port $PROXY_PORT is already in use by something else"; fi
  PROXY_PORT=$PROXY_PORT UPSTREAM_PORT=$REST_PORT nohup node "$HERE/proxy.mjs" > "$HERE/.proxy.log" 2>&1 &
  echo $! > "$PIDF"
  sleep 1
fi

apply_sql

# ---- smoke ----------------------------------------------------------------------------------------------------------
code=000
for _ in $(seq 1 20); do
  code="$(curl -s -o /dev/null -w '%{http_code}' -H "apikey: $SUPABASE_SERVICE_ROLE_KEY_ARCHIVE" -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY_ARCHIVE" "$URL/rest/v1/pos_orders?select=id&limit=1" || true)"
  [ "$code" = "200" ] && break
  sleep 1
done
[ "$code" = "200" ] || die "PostgREST smoke check returned $code (docker logs coop-local-rest)"

cat <<MSG
local Supabase is up (loopback only)
  API (supabase-js URL)  $URL       -> PostgREST on 127.0.0.1:${REST_PORT}
  Postgres               127.0.0.1:${DB_PORT} (psql via: docker exec -it $DB psql -U postgres)
  smoke check            GET /rest/v1/pos_orders returned 200
Run the dashboard against it (never against a hosted project):
  scripts/local-supabase/dev.sh
  (or: set -a; source scripts/local-supabase/.local-env; set +a; DEV_AUTH_BYPASS=true npm run dev)
Re-apply the SQL only: scripts/local-supabase/up.sh --reapply      Tear down: scripts/local-supabase/down.sh
MSG
