import type {RepricedVariant, RepriceHistoryEvent, RepriceRun} from './reprice-types';

// Representative mock run so the Repricer page renders sensibly with no
// Supabase env configured — one row per interesting outcome, not a full 48-row
// batch. Figures for the applied row are real examples from the batch job.
export const MOCK_REPRICE_RUN: RepriceRun = {
  runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
  ranAt: '2026-08-18T02:15:00.000Z',
  dryRun: true,
  rows: [
    {
      id: 'row-1',
      runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      marketplace: 'lazada',
      marketplaceSku: 'ZMY-AG243008',
      marketplaceTitle: 'Freeze Dried Superfood Munchies for Dogs and Cats Chicken & Cranberry',
      referencePrice: 169,
      referenceSource: 'lazada_special_price',
      listedPrice: 169,
      specialPrice: 169,
      shopifyVariantId: 'gid://shopify/ProductVariant/1001',
      shopifyTitle: 'Freeze Dried Superfood Munchies for Dogs and Cats Chicken & Cranberry',
      matchScore: 0.854,
      matchBand: 'auto',
      targetPrice: 135,
      floorPrice: 100,
      oldPrice: 143,
      newPrice: 135,
      guardrail: null,
      skipReason: null,
    },
    {
      id: 'row-2',
      runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      marketplace: 'lazada',
      marketplaceSku: 'ZMY-AG108812',
      marketplaceTitle: 'Grain Free Salmon Cat Food 1.5kg',
      referencePrice: 599,
      referenceSource: 'lazada_special_price',
      listedPrice: 599,
      specialPrice: 599,
      shopifyVariantId: 'gid://shopify/ProductVariant/1002',
      shopifyTitle: 'Grain Free Salmon Cat Food 1.5kg',
      matchScore: 0.91,
      matchBand: 'exact',
      targetPrice: 479,
      floorPrice: null,
      oldPrice: 520,
      newPrice: null,
      guardrail: 'no-floor',
      skipReason: null,
    },
    {
      id: 'row-3',
      runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      marketplace: 'lazada',
      marketplaceSku: 'ZMY-AG332210',
      marketplaceTitle: 'Dental Chew Sticks for Small Dogs 200g',
      referencePrice: 249,
      referenceSource: 'lazada_special_price',
      listedPrice: 249,
      specialPrice: 249,
      shopifyVariantId: 'gid://shopify/ProductVariant/1003',
      shopifyTitle: 'Dental Chew Sticks for Small Dogs 200g',
      matchScore: 0.88,
      matchBand: 'auto',
      targetPrice: 199,
      floorPrice: null,
      oldPrice: 219,
      newPrice: null,
      guardrail: 'no-floor',
      skipReason: null,
    },
    {
      id: 'row-4',
      runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      marketplace: 'lazada',
      marketplaceSku: 'ZMY-AG551190',
      marketplaceTitle: 'Cat Litter Clumping Bentonite 10L',
      referencePrice: 399,
      referenceSource: 'lazada_special_price',
      listedPrice: 399,
      specialPrice: 399,
      shopifyVariantId: 'gid://shopify/ProductVariant/1004',
      shopifyTitle: 'Cat Litter Clumping Bentonite 10L',
      matchScore: 0.92,
      matchBand: 'exact',
      targetPrice: 319,
      floorPrice: 300,
      oldPrice: 319,
      newPrice: 319,
      guardrail: 'no-op',
      skipReason: null,
    },
    {
      id: 'row-5',
      runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      marketplace: 'lazada',
      marketplaceSku: 'ZMY-AG778823',
      marketplaceTitle: 'Puppy Training Pads 60pcs',
      referencePrice: 450,
      referenceSource: 'lazada_special_price',
      listedPrice: 450,
      specialPrice: 450,
      shopifyVariantId: null,
      shopifyTitle: null,
      matchScore: 0.41,
      matchBand: 'ambiguous',
      targetPrice: null,
      floorPrice: null,
      oldPrice: null,
      newPrice: null,
      guardrail: null,
      skipReason: 'ambiguous',
    },
    {
      id: 'row-6',
      runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      marketplace: 'lazada',
      marketplaceSku: 'ZMY-AG990045',
      marketplaceTitle: 'Bird Cage Feeder Set',
      referencePrice: null,
      referenceSource: null,
      listedPrice: null,
      specialPrice: null,
      shopifyVariantId: 'gid://shopify/ProductVariant/1006',
      shopifyTitle: 'Bird Cage Feeder Set',
      matchScore: 0.6,
      matchBand: 'none',
      targetPrice: null,
      floorPrice: null,
      oldPrice: null,
      newPrice: null,
      guardrail: null,
      skipReason: 'listing-inactive',
    },
    {
      id: 'row-7',
      runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      marketplace: 'lazada',
      marketplaceSku: 'ZMY-AG221177',
      marketplaceTitle: 'Rabbit Hay Timothy Grass 1kg',
      referencePrice: 320,
      referenceSource: 'lazada_special_price',
      listedPrice: 320,
      specialPrice: 320,
      shopifyVariantId: 'gid://shopify/ProductVariant/1007',
      shopifyTitle: 'Rabbit Hay Timothy Grass 1kg',
      matchScore: 0.55,
      matchBand: 'review',
      targetPrice: 256,
      floorPrice: 220,
      oldPrice: 280,
      newPrice: null,
      guardrail: null,
      skipReason: 'needs-review',
    },
    {
      id: 'row-8',
      runId: '4b9c3a10-6e2a-4a7a-9a3a-1f0e2c8d5b11',
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      marketplace: 'lazada',
      marketplaceSku: 'ZMY-AG663302',
      marketplaceTitle: 'Fish Tank Air Pump Mini',
      referencePrice: 199,
      referenceSource: 'lazada_special_price',
      listedPrice: 199,
      specialPrice: 199,
      shopifyVariantId: null,
      shopifyTitle: null,
      matchScore: null,
      matchBand: 'none',
      targetPrice: null,
      floorPrice: null,
      oldPrice: null,
      newPrice: null,
      guardrail: null,
      skipReason: 'unmatched',
    },
  ],
};

// Variants the repricer has actually applied a price to, in prior runs
// (earlier than MOCK_REPRICE_RUN, which is a no-op dry run). Newest first —
// mirrors what getRepricedVariants() returns from Supabase.
// Variant 1001 demonstrates the exact incident this feature exists to catch:
// the repricer's audit trail says it last set ₱135, but the latest run's
// old_price read of Shopify shows ₱143 — a write that never actually landed
// (or was hand-edited afterwards), so the history panel has to name that gap.
// Variant 1002 is the healthy case: one recorded change, no drift. Variant
// 1003 has never had a qualifying change recorded at all — its history panel
// must say so plainly rather than look broken.
export const MOCK_REPRICED_VARIANTS: RepricedVariant[] = [
  {
    shopifyVariantId: 'gid://shopify/ProductVariant/1001',
    shopifyTitle: 'Freeze Dried Superfood Munchies for Dogs and Cats Chicken & Cranberry',
    marketplaceTitle: 'Freeze Dried Superfood Munchies for Dogs and Cats Chicken & Cranberry',
    marketplaceSku: 'ZMY-AG243008',
    referencePrice: 169,
    oldPrice: 149,
    newPrice: 135,
    discountPct: 20,
    ranAt: '2026-08-17T05:50:00.000Z',
    currentPrice: 143,
    drifted: true,
  },
  {
    shopifyVariantId: 'gid://shopify/ProductVariant/1002',
    shopifyTitle: 'Grain Free Salmon Cat Food 1.5kg',
    marketplaceTitle: 'Grain Free Salmon Cat Food 1.5kg',
    marketplaceSku: 'ZMY-AG108812',
    referencePrice: 599,
    oldPrice: 520,
    newPrice: 479,
    discountPct: 20,
    ranAt: '2026-08-10T03:20:00.000Z',
    currentPrice: 479,
    drifted: false,
  },
  {
    shopifyVariantId: 'gid://shopify/ProductVariant/1003',
    shopifyTitle: 'Cat Litter Clumping Bentonite 10L',
    marketplaceTitle: 'Cat Litter Clumping Bentonite 10L',
    marketplaceSku: 'ZMY-AG551190',
    referencePrice: 399,
    oldPrice: 319,
    newPrice: 319,
    discountPct: 20,
    ranAt: '2026-08-04T03:20:00.000Z',
    currentPrice: 319,
    drifted: false,
  },
];

// Price-change timelines for the "Currently repriced" variants above,
// newest-first. Variant 1001 mixes a preview, the applied change it recorded
// (₱135), and an older no-op run — appliedChanges() keeps only the one real
// change, and the panel's drift notice separately explains the ₱143 Shopify
// actually holds now (a write whose audit row was never recorded). Variant
// 1002 has exactly one recorded change, undrifted, for the unremarkable
// case. Variant 1003 has rows in the audit trail, but none of them are a
// real applied change (a preview and a no-op) — appliedChanges() filters
// down to nothing, demonstrating the "no recorded price changes yet" state.
export const MOCK_VARIANT_HISTORY: Record<string, RepriceHistoryEvent[]> = {
  'gid://shopify/ProductVariant/1001': [
    {
      ranAt: '2026-08-26T11:36:25.000Z',
      dryRun: false,
      applied: true,
      referencePrice: 126,
      targetPrice: 126,
      oldPrice: 120,
      newPrice: 126,
      guardrail: null,
      skipReason: null,
      matchBand: 'auto',
      note: 'Reconstructed on 2026-08-26. This change reached Shopify but its audit write was rejected at the time due to a missing column; the price and timestamp below were read back from Shopify directly.',
    },
    {
      ranAt: '2026-08-18T02:15:00.000Z',
      dryRun: true,
      applied: false,
      referencePrice: 169,
      targetPrice: 135,
      oldPrice: 149,
      newPrice: 135,
      guardrail: null,
      skipReason: null,
      matchBand: 'auto',
      note: null,
    },
    {
      ranAt: '2026-08-17T05:50:00.000Z',
      dryRun: false,
      applied: true,
      referencePrice: 169,
      targetPrice: 135,
      oldPrice: 149,
      newPrice: 135,
      guardrail: null,
      skipReason: null,
      matchBand: 'auto',
      note: null,
    },
    {
      ranAt: '2026-08-12T05:50:00.000Z',
      dryRun: false,
      applied: true,
      referencePrice: 172,
      targetPrice: 149,
      oldPrice: 149,
      newPrice: 149,
      guardrail: 'no-op',
      skipReason: null,
      matchBand: 'auto',
      note: null,
    },
  ],
  'gid://shopify/ProductVariant/1002': [
    {
      ranAt: '2026-08-10T03:20:00.000Z',
      dryRun: false,
      applied: true,
      referencePrice: 599,
      targetPrice: 479,
      oldPrice: 520,
      newPrice: 479,
      guardrail: null,
      skipReason: null,
      matchBand: 'exact',
      note: null,
    },
    {
      ranAt: '2026-08-03T03:20:00.000Z',
      dryRun: true,
      applied: false,
      referencePrice: 610,
      targetPrice: 520,
      oldPrice: 520,
      newPrice: 520,
      guardrail: 'no-op',
      skipReason: null,
      matchBand: 'exact',
      note: null,
    },
  ],
  'gid://shopify/ProductVariant/1003': [
    {
      ranAt: '2026-08-04T03:20:00.000Z',
      dryRun: true,
      applied: false,
      referencePrice: 399,
      targetPrice: 319,
      oldPrice: 319,
      newPrice: 319,
      guardrail: null,
      skipReason: null,
      matchBand: 'exact',
      note: null,
    },
    {
      ranAt: '2026-07-28T03:20:00.000Z',
      dryRun: false,
      applied: true,
      referencePrice: 399,
      targetPrice: 319,
      oldPrice: 319,
      newPrice: 319,
      guardrail: 'no-op',
      skipReason: null,
      matchBand: 'exact',
      note: null,
    },
  ],
};
